//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturuldu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Havaalani {
    
    
    public partial class SiteMaster {
        
        /// <summary>
        /// MainContent denetimi.
        /// </summary>
        /// <remarks>
        ///Otomatik olarak oluşturulan alan.
        /// Tasarımcı dosyasından arka plan kod dosyasına alan taşıma bildiriminde değişiklik yapmak için.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}
